const languageList = {
  "en-US": {
    logout: "Logout",
    gptSearch: "GPT Search",
    home: "Home",
    play: "Play",
    moreInfo: "More Info",
    nowPlaying: "Now playing",
    topRated: "Top rated",
    popular: "Popular",
    upComing: "Upcoming",
    placeHolder: "What would you like to watch today ?",
    search: "Search",
  },
  "ru-RU": {
    logout: "выйти",
    gptSearch: "GPT-поиск",
    home: "Дом",
    play: "Играть",
    moreInfo: "Больше информации",
    nowPlaying: "Сейчас играет",
    topRated: "Самые популярные",
    popular: "Популярный",
    upComing: "Предстоящие",
    placeHolder: "Что бы вы хотели посмотреть сегодня?",
    search: "поиск",
  },
  "ja-JP": {
    logout: "ログアウト",
    gptSearch: "GPT 検索",
    home: "家",
    play: "遊ぶ",
    moreInfo: "より詳しい情報",
    nowPlaying: "再生中",
    topRated: "トップレート",
    popular: "人気のある",
    upComing: "今後の予定",
    placeHolder: "今日は何を見たいですか？",
    search: "検索",
  },
  "zh-CN": {
    logout: "登出",
    gptSearch: "GPT 搜索",
    home: "家",
    play: "玩",
    moreInfo: "更多信息",
    nowPlaying: "正在播放",
    topRated: "评价最高",
    popular: "受欢迎的",
    upComing: "即将推出",
    placeHolder: "今天你想看什么？",
    search: "搜索",
  },
};

export default languageList;
